version: "3.7"
services:
  redis:
    image: redis:7
    container_name: redis_app
    command: --port 5370
    expose:
      - 5370

  app:
    build:
      context: .
    env_file:
      - .env
    container_name: fastapi_app
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./app:/app
    ports:
      - 9999:8000
    depends_on:
      - redis
